CREATE TABLE outbox
(
    outbox_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    partition_key INT,
    event_type VARCHAR(40),
    payload JSON,
    published TINYINT(1) NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
